#!/bin/bash
MYUSERNAME=yashasvi
MYPASSWORD=Yashasvi31!
y=date
STARTOFSCRIPT=$(date)
ENDOFSCRIPT=$(date)
echo " MYUSERNAME :$MYUSERNAME"
echo " MYPASSWORD : $MYPASSWORD "
echo " STARTOFSCRIPT : $STARTOFSCRIPT "
echo " ENDOFSCRIPT : $ENDOFSCRIPT "
